### ISSUE TITLE
not functional since outage?

### ISSUE THREAD

**Issue by blysik** [evancg37/Alexa-Pool-Control#3]
I was using this code successfully.  Then iAqualink had that multi-day outage, and the code no longer seems to be successful at turning on my spa.

Are you seeing this behavior as well?  Thanks.

**Comment by blysik** [comment]
This is the error I see:

```
Error: Unknown state derived from element spa_pump_state in checkElementToggle.
Error: Unknown state derived from element spa_heater_state in checkElementToggle.
```

**Comment by blysik** [comment]
Looks like they updated things.   These are the new button image src values that work:

```
AQUA_TOGGLE_ON = 'https://mobile.iaqualink.net/files/images/aux_0_1.png'
AQUA_TOGGLE_OFF = 'https://mobile.iaqualink.net/files/images/aux_0_0.png'
AQUA_TOGGLE_ALTERNATE = 'https://mobile.iaqualink.net/files/images/aux_0_3.png'
```

**Comment by evancg37** [comment]
Thank you so much for finding out what the new image source urls are! I was pressing Inspect Element on the buttons myself in Chrome when I got your message. 

It's good they didn't change much else. If they completely redid the site the script would have to be remade.

**Comment by blysik** [comment]
I hear someone is investigating reverse-engineering the API.  Maybe we'll get the ability to use that instead.  But for now, thanks for your work!

**Comment by evancg37** [comment]
No problem! And yeah I actually hope the API route works out because I don't have a pool to use or test things like this on anymore haha.
